
    {nome: "João", media: 96},
    {nome: 'Maria', media: 90},
    {nome: 'Pedro', media: 80},
    {nome: 'Ana', media: 70},
    {nome: 'Gustavo', media: 60},
    {nome: 'Luis', media: 50},
    {nome: 'Rafael', media: 40},
    {nome: 'Lucas', media: 30},
    {nome: 'Mateus', media: 20},
    {nome: 'Gabriel', media: 10},